#!/usr/bin/env python3
"""Convert the markdown report to a self-contained HTML file with embedded images."""
import base64
import os
import re
import markdown

REPORT_DIR = '/home/roger/Desktop/auto-craftax/report'
MD_PATH = os.path.join(REPORT_DIR, 'report.md')
HTML_PATH = os.path.join(REPORT_DIR, 'report.html')
PLOTS_DIR = os.path.join(REPORT_DIR, 'plots')

# Read markdown
with open(MD_PATH, 'r') as f:
    md_content = f.read()

# Replace image references with base64 embedded images
def embed_image(match):
    alt = match.group(1)
    path = match.group(2)
    # Resolve relative path
    if not os.path.isabs(path):
        abs_path = os.path.join(REPORT_DIR, path)
    else:
        abs_path = path

    if os.path.exists(abs_path):
        with open(abs_path, 'rb') as f:
            img_data = base64.b64encode(f.read()).decode('utf-8')
        ext = os.path.splitext(abs_path)[1].lower()
        mime = {'png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif', '.svg': 'image/svg+xml'}
        mime_type = mime.get(ext, 'image/png')
        return f'![{alt}](data:{mime_type};base64,{img_data})'
    return match.group(0)

md_content = re.sub(r'!\[([^\]]*)\]\(([^)]+)\)', embed_image, md_content)

# Convert to HTML
html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code', 'toc', 'nl2br'])

# Build self-contained HTML
html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Craftax Research Report</title>
<style>
  :root {{
    --bg: #ffffff;
    --fg: #1a1a2e;
    --accent: #2c3e50;
    --border: #ddd;
    --code-bg: #f4f4f8;
    --table-head: #2c3e50;
    --table-stripe: #f8f9fa;
    --link: #2980b9;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.7;
    color: var(--fg);
    background: var(--bg);
    max-width: 1000px;
    margin: 0 auto;
    padding: 2rem 3rem;
    font-size: 15px;
  }}
  h1 {{
    font-size: 2em;
    color: var(--accent);
    border-bottom: 3px solid var(--accent);
    padding-bottom: 0.5em;
    margin-top: 2em;
  }}
  h1:first-of-type {{ margin-top: 0; }}
  h2 {{
    font-size: 1.5em;
    color: var(--accent);
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.3em;
    margin-top: 2em;
  }}
  h3 {{
    font-size: 1.2em;
    color: #34495e;
    margin-top: 1.5em;
  }}
  p {{ margin: 0.8em 0; }}
  strong {{ color: #1a1a2e; }}
  a {{ color: var(--link); text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  img {{
    max-width: 100%;
    height: auto;
    display: block;
    margin: 1.5em auto;
    border: 1px solid var(--border);
    border-radius: 4px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }}
  table {{
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-size: 0.9em;
  }}
  thead th {{
    background: var(--table-head);
    color: white;
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
  }}
  tbody td {{
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
  }}
  tbody tr:nth-child(even) {{ background: var(--table-stripe); }}
  tbody tr:hover {{ background: #eef2f7; }}
  code {{
    font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
    background: var(--code-bg);
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.9em;
  }}
  pre {{
    background: var(--code-bg);
    padding: 1em 1.5em;
    border-radius: 6px;
    overflow-x: auto;
    border: 1px solid var(--border);
  }}
  pre code {{ background: none; padding: 0; }}
  hr {{
    border: none;
    border-top: 2px solid var(--border);
    margin: 2em 0;
  }}
  blockquote {{
    border-left: 4px solid var(--accent);
    margin: 1em 0;
    padding: 0.5em 1em;
    background: #f8f9fa;
    color: #555;
  }}
  .container {{ max-width: 1000px; margin: 0 auto; }}

  @media print {{
    body {{ font-size: 12px; padding: 1cm; }}
    img {{ max-width: 100%; page-break-inside: avoid; }}
    table {{ page-break-inside: avoid; }}
    h2, h3 {{ page-break-after: avoid; }}
  }}

  @media (max-width: 768px) {{
    body {{ padding: 1rem; font-size: 14px; }}
    table {{ font-size: 0.8em; }}
    thead th, tbody td {{ padding: 6px 8px; }}
  }}
</style>
</head>
<body>
{html_body}
<footer style="margin-top: 3em; padding-top: 1em; border-top: 1px solid #ddd; color: #888; font-size: 0.85em;">
  <p>Generated by autonomous research agent using xgenius. Report date: March 20, 2026.</p>
</footer>
</body>
</html>'''

with open(HTML_PATH, 'w') as f:
    f.write(html)

print(f"HTML report saved to {HTML_PATH}")
print(f"File size: {os.path.getsize(HTML_PATH) / 1024 / 1024:.1f} MB")
